/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.sales.engine.kafka.avro.model;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class CouponRedeemedAvroModel extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -5701785991198601361L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"CouponRedeemedAvroModel\",\"namespace\":\"com.sales.engine.kafka.avro.model\",\"fields\":[{\"name\":\"couponUuid\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"logicalType\":\"UUID\"},{\"name\":\"redeemedAt\",\"type\":[\"null\",\"long\"],\"logicalType\":[\"null\",\"date\"]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<CouponRedeemedAvroModel> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<CouponRedeemedAvroModel> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<CouponRedeemedAvroModel> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<CouponRedeemedAvroModel> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<CouponRedeemedAvroModel> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this CouponRedeemedAvroModel to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a CouponRedeemedAvroModel from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a CouponRedeemedAvroModel instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static CouponRedeemedAvroModel fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.String couponUuid;
  private java.lang.Long redeemedAt;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public CouponRedeemedAvroModel() {}

  /**
   * All-args constructor.
   * @param couponUuid The new value for couponUuid
   * @param redeemedAt The new value for redeemedAt
   */
  public CouponRedeemedAvroModel(java.lang.String couponUuid, java.lang.Long redeemedAt) {
    this.couponUuid = couponUuid;
    this.redeemedAt = redeemedAt;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return couponUuid;
    case 1: return redeemedAt;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: couponUuid = value$ != null ? value$.toString() : null; break;
    case 1: redeemedAt = (java.lang.Long)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'couponUuid' field.
   * @return The value of the 'couponUuid' field.
   */
  public java.lang.String getCouponUuid() {
    return couponUuid;
  }


  /**
   * Sets the value of the 'couponUuid' field.
   * @param value the value to set.
   */
  public void setCouponUuid(java.lang.String value) {
    this.couponUuid = value;
  }

  /**
   * Gets the value of the 'redeemedAt' field.
   * @return The value of the 'redeemedAt' field.
   */
  public java.lang.Long getRedeemedAt() {
    return redeemedAt;
  }


  /**
   * Sets the value of the 'redeemedAt' field.
   * @param value the value to set.
   */
  public void setRedeemedAt(java.lang.Long value) {
    this.redeemedAt = value;
  }

  /**
   * Creates a new CouponRedeemedAvroModel RecordBuilder.
   * @return A new CouponRedeemedAvroModel RecordBuilder
   */
  public static com.sales.engine.kafka.avro.model.CouponRedeemedAvroModel.Builder newBuilder() {
    return new com.sales.engine.kafka.avro.model.CouponRedeemedAvroModel.Builder();
  }

  /**
   * Creates a new CouponRedeemedAvroModel RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new CouponRedeemedAvroModel RecordBuilder
   */
  public static com.sales.engine.kafka.avro.model.CouponRedeemedAvroModel.Builder newBuilder(com.sales.engine.kafka.avro.model.CouponRedeemedAvroModel.Builder other) {
    if (other == null) {
      return new com.sales.engine.kafka.avro.model.CouponRedeemedAvroModel.Builder();
    } else {
      return new com.sales.engine.kafka.avro.model.CouponRedeemedAvroModel.Builder(other);
    }
  }

  /**
   * Creates a new CouponRedeemedAvroModel RecordBuilder by copying an existing CouponRedeemedAvroModel instance.
   * @param other The existing instance to copy.
   * @return A new CouponRedeemedAvroModel RecordBuilder
   */
  public static com.sales.engine.kafka.avro.model.CouponRedeemedAvroModel.Builder newBuilder(com.sales.engine.kafka.avro.model.CouponRedeemedAvroModel other) {
    if (other == null) {
      return new com.sales.engine.kafka.avro.model.CouponRedeemedAvroModel.Builder();
    } else {
      return new com.sales.engine.kafka.avro.model.CouponRedeemedAvroModel.Builder(other);
    }
  }

  /**
   * RecordBuilder for CouponRedeemedAvroModel instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<CouponRedeemedAvroModel>
    implements org.apache.avro.data.RecordBuilder<CouponRedeemedAvroModel> {

    private java.lang.String couponUuid;
    private java.lang.Long redeemedAt;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.sales.engine.kafka.avro.model.CouponRedeemedAvroModel.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.couponUuid)) {
        this.couponUuid = data().deepCopy(fields()[0].schema(), other.couponUuid);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.redeemedAt)) {
        this.redeemedAt = data().deepCopy(fields()[1].schema(), other.redeemedAt);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
    }

    /**
     * Creates a Builder by copying an existing CouponRedeemedAvroModel instance
     * @param other The existing instance to copy.
     */
    private Builder(com.sales.engine.kafka.avro.model.CouponRedeemedAvroModel other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.couponUuid)) {
        this.couponUuid = data().deepCopy(fields()[0].schema(), other.couponUuid);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.redeemedAt)) {
        this.redeemedAt = data().deepCopy(fields()[1].schema(), other.redeemedAt);
        fieldSetFlags()[1] = true;
      }
    }

    /**
      * Gets the value of the 'couponUuid' field.
      * @return The value.
      */
    public java.lang.String getCouponUuid() {
      return couponUuid;
    }


    /**
      * Sets the value of the 'couponUuid' field.
      * @param value The value of 'couponUuid'.
      * @return This builder.
      */
    public com.sales.engine.kafka.avro.model.CouponRedeemedAvroModel.Builder setCouponUuid(java.lang.String value) {
      validate(fields()[0], value);
      this.couponUuid = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'couponUuid' field has been set.
      * @return True if the 'couponUuid' field has been set, false otherwise.
      */
    public boolean hasCouponUuid() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'couponUuid' field.
      * @return This builder.
      */
    public com.sales.engine.kafka.avro.model.CouponRedeemedAvroModel.Builder clearCouponUuid() {
      couponUuid = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'redeemedAt' field.
      * @return The value.
      */
    public java.lang.Long getRedeemedAt() {
      return redeemedAt;
    }


    /**
      * Sets the value of the 'redeemedAt' field.
      * @param value The value of 'redeemedAt'.
      * @return This builder.
      */
    public com.sales.engine.kafka.avro.model.CouponRedeemedAvroModel.Builder setRedeemedAt(java.lang.Long value) {
      validate(fields()[1], value);
      this.redeemedAt = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'redeemedAt' field has been set.
      * @return True if the 'redeemedAt' field has been set, false otherwise.
      */
    public boolean hasRedeemedAt() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'redeemedAt' field.
      * @return This builder.
      */
    public com.sales.engine.kafka.avro.model.CouponRedeemedAvroModel.Builder clearRedeemedAt() {
      redeemedAt = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public CouponRedeemedAvroModel build() {
      try {
        CouponRedeemedAvroModel record = new CouponRedeemedAvroModel();
        record.couponUuid = fieldSetFlags()[0] ? this.couponUuid : (java.lang.String) defaultValue(fields()[0]);
        record.redeemedAt = fieldSetFlags()[1] ? this.redeemedAt : (java.lang.Long) defaultValue(fields()[1]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<CouponRedeemedAvroModel>
    WRITER$ = (org.apache.avro.io.DatumWriter<CouponRedeemedAvroModel>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<CouponRedeemedAvroModel>
    READER$ = (org.apache.avro.io.DatumReader<CouponRedeemedAvroModel>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.couponUuid);

    if (this.redeemedAt == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeLong(this.redeemedAt);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.couponUuid = in.readString();

      if (in.readIndex() != 1) {
        in.readNull();
        this.redeemedAt = null;
      } else {
        this.redeemedAt = in.readLong();
      }

    } else {
      for (int i = 0; i < 2; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.couponUuid = in.readString();
          break;

        case 1:
          if (in.readIndex() != 1) {
            in.readNull();
            this.redeemedAt = null;
          } else {
            this.redeemedAt = in.readLong();
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










