/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.sales.engine.kafka.avro.model;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class CouponCreatedAvroModel extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 3020194137101476734L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"CouponCreatedAvroModel\",\"namespace\":\"com.sales.engine.kafka.avro.model\",\"fields\":[{\"name\":\"couponUuid\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"logicalType\":\"UUID\"},{\"name\":\"promoCode\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"}},{\"name\":\"companyUuid\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"logicalType\":\"UUID\"},{\"name\":\"companyName\",\"type\":[\"null\",{\"type\":\"string\",\"avro.java.string\":\"String\"}]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<CouponCreatedAvroModel> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<CouponCreatedAvroModel> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<CouponCreatedAvroModel> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<CouponCreatedAvroModel> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<CouponCreatedAvroModel> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this CouponCreatedAvroModel to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a CouponCreatedAvroModel from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a CouponCreatedAvroModel instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static CouponCreatedAvroModel fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.String couponUuid;
  private java.lang.String promoCode;
  private java.lang.String companyUuid;
  private java.lang.String companyName;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public CouponCreatedAvroModel() {}

  /**
   * All-args constructor.
   * @param couponUuid The new value for couponUuid
   * @param promoCode The new value for promoCode
   * @param companyUuid The new value for companyUuid
   * @param companyName The new value for companyName
   */
  public CouponCreatedAvroModel(java.lang.String couponUuid, java.lang.String promoCode, java.lang.String companyUuid, java.lang.String companyName) {
    this.couponUuid = couponUuid;
    this.promoCode = promoCode;
    this.companyUuid = companyUuid;
    this.companyName = companyName;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return couponUuid;
    case 1: return promoCode;
    case 2: return companyUuid;
    case 3: return companyName;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: couponUuid = value$ != null ? value$.toString() : null; break;
    case 1: promoCode = value$ != null ? value$.toString() : null; break;
    case 2: companyUuid = value$ != null ? value$.toString() : null; break;
    case 3: companyName = value$ != null ? value$.toString() : null; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'couponUuid' field.
   * @return The value of the 'couponUuid' field.
   */
  public java.lang.String getCouponUuid() {
    return couponUuid;
  }


  /**
   * Sets the value of the 'couponUuid' field.
   * @param value the value to set.
   */
  public void setCouponUuid(java.lang.String value) {
    this.couponUuid = value;
  }

  /**
   * Gets the value of the 'promoCode' field.
   * @return The value of the 'promoCode' field.
   */
  public java.lang.String getPromoCode() {
    return promoCode;
  }


  /**
   * Sets the value of the 'promoCode' field.
   * @param value the value to set.
   */
  public void setPromoCode(java.lang.String value) {
    this.promoCode = value;
  }

  /**
   * Gets the value of the 'companyUuid' field.
   * @return The value of the 'companyUuid' field.
   */
  public java.lang.String getCompanyUuid() {
    return companyUuid;
  }


  /**
   * Sets the value of the 'companyUuid' field.
   * @param value the value to set.
   */
  public void setCompanyUuid(java.lang.String value) {
    this.companyUuid = value;
  }

  /**
   * Gets the value of the 'companyName' field.
   * @return The value of the 'companyName' field.
   */
  public java.lang.String getCompanyName() {
    return companyName;
  }


  /**
   * Sets the value of the 'companyName' field.
   * @param value the value to set.
   */
  public void setCompanyName(java.lang.String value) {
    this.companyName = value;
  }

  /**
   * Creates a new CouponCreatedAvroModel RecordBuilder.
   * @return A new CouponCreatedAvroModel RecordBuilder
   */
  public static com.sales.engine.kafka.avro.model.CouponCreatedAvroModel.Builder newBuilder() {
    return new com.sales.engine.kafka.avro.model.CouponCreatedAvroModel.Builder();
  }

  /**
   * Creates a new CouponCreatedAvroModel RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new CouponCreatedAvroModel RecordBuilder
   */
  public static com.sales.engine.kafka.avro.model.CouponCreatedAvroModel.Builder newBuilder(com.sales.engine.kafka.avro.model.CouponCreatedAvroModel.Builder other) {
    if (other == null) {
      return new com.sales.engine.kafka.avro.model.CouponCreatedAvroModel.Builder();
    } else {
      return new com.sales.engine.kafka.avro.model.CouponCreatedAvroModel.Builder(other);
    }
  }

  /**
   * Creates a new CouponCreatedAvroModel RecordBuilder by copying an existing CouponCreatedAvroModel instance.
   * @param other The existing instance to copy.
   * @return A new CouponCreatedAvroModel RecordBuilder
   */
  public static com.sales.engine.kafka.avro.model.CouponCreatedAvroModel.Builder newBuilder(com.sales.engine.kafka.avro.model.CouponCreatedAvroModel other) {
    if (other == null) {
      return new com.sales.engine.kafka.avro.model.CouponCreatedAvroModel.Builder();
    } else {
      return new com.sales.engine.kafka.avro.model.CouponCreatedAvroModel.Builder(other);
    }
  }

  /**
   * RecordBuilder for CouponCreatedAvroModel instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<CouponCreatedAvroModel>
    implements org.apache.avro.data.RecordBuilder<CouponCreatedAvroModel> {

    private java.lang.String couponUuid;
    private java.lang.String promoCode;
    private java.lang.String companyUuid;
    private java.lang.String companyName;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.sales.engine.kafka.avro.model.CouponCreatedAvroModel.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.couponUuid)) {
        this.couponUuid = data().deepCopy(fields()[0].schema(), other.couponUuid);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.promoCode)) {
        this.promoCode = data().deepCopy(fields()[1].schema(), other.promoCode);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.companyUuid)) {
        this.companyUuid = data().deepCopy(fields()[2].schema(), other.companyUuid);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.companyName)) {
        this.companyName = data().deepCopy(fields()[3].schema(), other.companyName);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
    }

    /**
     * Creates a Builder by copying an existing CouponCreatedAvroModel instance
     * @param other The existing instance to copy.
     */
    private Builder(com.sales.engine.kafka.avro.model.CouponCreatedAvroModel other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.couponUuid)) {
        this.couponUuid = data().deepCopy(fields()[0].schema(), other.couponUuid);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.promoCode)) {
        this.promoCode = data().deepCopy(fields()[1].schema(), other.promoCode);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.companyUuid)) {
        this.companyUuid = data().deepCopy(fields()[2].schema(), other.companyUuid);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.companyName)) {
        this.companyName = data().deepCopy(fields()[3].schema(), other.companyName);
        fieldSetFlags()[3] = true;
      }
    }

    /**
      * Gets the value of the 'couponUuid' field.
      * @return The value.
      */
    public java.lang.String getCouponUuid() {
      return couponUuid;
    }


    /**
      * Sets the value of the 'couponUuid' field.
      * @param value The value of 'couponUuid'.
      * @return This builder.
      */
    public com.sales.engine.kafka.avro.model.CouponCreatedAvroModel.Builder setCouponUuid(java.lang.String value) {
      validate(fields()[0], value);
      this.couponUuid = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'couponUuid' field has been set.
      * @return True if the 'couponUuid' field has been set, false otherwise.
      */
    public boolean hasCouponUuid() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'couponUuid' field.
      * @return This builder.
      */
    public com.sales.engine.kafka.avro.model.CouponCreatedAvroModel.Builder clearCouponUuid() {
      couponUuid = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'promoCode' field.
      * @return The value.
      */
    public java.lang.String getPromoCode() {
      return promoCode;
    }


    /**
      * Sets the value of the 'promoCode' field.
      * @param value The value of 'promoCode'.
      * @return This builder.
      */
    public com.sales.engine.kafka.avro.model.CouponCreatedAvroModel.Builder setPromoCode(java.lang.String value) {
      validate(fields()[1], value);
      this.promoCode = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'promoCode' field has been set.
      * @return True if the 'promoCode' field has been set, false otherwise.
      */
    public boolean hasPromoCode() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'promoCode' field.
      * @return This builder.
      */
    public com.sales.engine.kafka.avro.model.CouponCreatedAvroModel.Builder clearPromoCode() {
      promoCode = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'companyUuid' field.
      * @return The value.
      */
    public java.lang.String getCompanyUuid() {
      return companyUuid;
    }


    /**
      * Sets the value of the 'companyUuid' field.
      * @param value The value of 'companyUuid'.
      * @return This builder.
      */
    public com.sales.engine.kafka.avro.model.CouponCreatedAvroModel.Builder setCompanyUuid(java.lang.String value) {
      validate(fields()[2], value);
      this.companyUuid = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'companyUuid' field has been set.
      * @return True if the 'companyUuid' field has been set, false otherwise.
      */
    public boolean hasCompanyUuid() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'companyUuid' field.
      * @return This builder.
      */
    public com.sales.engine.kafka.avro.model.CouponCreatedAvroModel.Builder clearCompanyUuid() {
      companyUuid = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'companyName' field.
      * @return The value.
      */
    public java.lang.String getCompanyName() {
      return companyName;
    }


    /**
      * Sets the value of the 'companyName' field.
      * @param value The value of 'companyName'.
      * @return This builder.
      */
    public com.sales.engine.kafka.avro.model.CouponCreatedAvroModel.Builder setCompanyName(java.lang.String value) {
      validate(fields()[3], value);
      this.companyName = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'companyName' field has been set.
      * @return True if the 'companyName' field has been set, false otherwise.
      */
    public boolean hasCompanyName() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'companyName' field.
      * @return This builder.
      */
    public com.sales.engine.kafka.avro.model.CouponCreatedAvroModel.Builder clearCompanyName() {
      companyName = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public CouponCreatedAvroModel build() {
      try {
        CouponCreatedAvroModel record = new CouponCreatedAvroModel();
        record.couponUuid = fieldSetFlags()[0] ? this.couponUuid : (java.lang.String) defaultValue(fields()[0]);
        record.promoCode = fieldSetFlags()[1] ? this.promoCode : (java.lang.String) defaultValue(fields()[1]);
        record.companyUuid = fieldSetFlags()[2] ? this.companyUuid : (java.lang.String) defaultValue(fields()[2]);
        record.companyName = fieldSetFlags()[3] ? this.companyName : (java.lang.String) defaultValue(fields()[3]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<CouponCreatedAvroModel>
    WRITER$ = (org.apache.avro.io.DatumWriter<CouponCreatedAvroModel>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<CouponCreatedAvroModel>
    READER$ = (org.apache.avro.io.DatumReader<CouponCreatedAvroModel>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.couponUuid);

    out.writeString(this.promoCode);

    out.writeString(this.companyUuid);

    if (this.companyName == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.companyName);
    }

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.couponUuid = in.readString();

      this.promoCode = in.readString();

      this.companyUuid = in.readString();

      if (in.readIndex() != 1) {
        in.readNull();
        this.companyName = null;
      } else {
        this.companyName = in.readString();
      }

    } else {
      for (int i = 0; i < 4; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.couponUuid = in.readString();
          break;

        case 1:
          this.promoCode = in.readString();
          break;

        case 2:
          this.companyUuid = in.readString();
          break;

        case 3:
          if (in.readIndex() != 1) {
            in.readNull();
            this.companyName = null;
          } else {
            this.companyName = in.readString();
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










